#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import calendar, datetime, json, shutil, re

ROOT = Path(__file__).resolve().parents[1]
TDIR = ROOT/'theories'/'sound_tiers'
ADIR = ROOT/'theories'/'ablation_variants'
TDIR.mkdir(parents=True, exist_ok=True)
ADIR.mkdir(parents=True, exist_ok=True)

HEADER = r'''% ==============================================================================
% SOUND GREGORIAN TEMPORAL THEORY -- GENERATED ARTIFACT
% Generated by scripts/build_sound_tiers.py
% Intended years are positive Gregorian years (proleptic Gregorian semantics).
% IMPORTANT: Historical Best0/Best1/SAFE_HEAVY files are preserved separately
% and are not the formal T1/T2/T3 files used in the new experiments.
% ==============================================================================
'''

T1 = HEADER + r'''
% --- Types and constructors ---
tff(t_date, type, date: $tType).
tff(t_ymd, type, ymd: ($int * $int * $int) > date).
tff(t_day_name, type, day_name: $tType).
tff(dn_sun, type, sunday: day_name).
tff(dn_mon, type, monday: day_name).
tff(dn_tue, type, tuesday: day_name).
tff(dn_wed, type, wednesday: day_name).
tff(dn_thu, type, thursday: day_name).
tff(dn_fri, type, friday: day_name).
tff(dn_sat, type, saturday: day_name).

tff(day_names_distinct, axiom,
  $distinct(sunday,monday,tuesday,wednesday,thursday,friday,saturday)).

tff(ymd_injective, axiom,
  ![Y1:$int,M1:$int,D1:$int,Y2:$int,M2:$int,D2:$int]:
    (ymd(Y1,M1,D1)=ymd(Y2,M2,D2) => (Y1=Y2 & M1=M2 & D1=D2))).

% --- Structural predicates ---
tff(t_leap, type, is_leap_year: $int > $o).
tff(t_dim, type, is_days_in_month: ($int * $int * $int) > $o).
tff(t_diy, type, is_days_in_year: ($int * $int) > $o).
tff(t_valid_date, type, valid_date: ($int * $int * $int) > $o).
tff(t_weekday, type, weekday: (date * day_name) > $o).
tff(t_map_i2n, type, map_iso: ($int * day_name) > $o).
tff(t_map_n2i, type, map_name_to_int: (day_name * $int) > $o).

% Gregorian leap-year rule, stated as a definition for positive years.
tff(leap_year_def, axiom,
  ![Y:$int]:
   (is_leap_year(Y) <=>
    ($greater(Y,0) & $remainder_e(Y,4)=0 &
      ($remainder_e(Y,100)!=0 | $remainder_e(Y,400)=0)))).

% Month-length relation is exact, not merely one-way.
tff(month_1_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(1,Y,L) <=> L=31)).
tff(month_2_def, axiom,
  ![Y:$int,L:$int]:
   (is_days_in_month(2,Y,L) <=>
    ((is_leap_year(Y) & L=29) | (~is_leap_year(Y) & L=28)))).
tff(month_3_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(3,Y,L) <=> L=31)).
tff(month_4_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(4,Y,L) <=> L=30)).
tff(month_5_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(5,Y,L) <=> L=31)).
tff(month_6_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(6,Y,L) <=> L=30)).
tff(month_7_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(7,Y,L) <=> L=31)).
tff(month_8_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(8,Y,L) <=> L=31)).
tff(month_9_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(9,Y,L) <=> L=30)).
tff(month_10_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(10,Y,L) <=> L=31)).
tff(month_11_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(11,Y,L) <=> L=30)).
tff(month_12_def, axiom, ![Y:$int,L:$int]: (is_days_in_month(12,Y,L) <=> L=31)).
tff(month_domain, axiom,
  ![M:$int,Y:$int,L:$int]:
   (is_days_in_month(M,Y,L) => ($lesseq(1,M) & $lesseq(M,12)))).

tff(year_length_def, axiom,
  ![Y:$int,L:$int]:
   (is_days_in_year(Y,L) <=>
    ((is_leap_year(Y) & L=366) | (~is_leap_year(Y) & $greater(Y,0) & L=365)))).

tff(valid_date_def, axiom,
  ![Y:$int,M:$int,D:$int]:
   (valid_date(Y,M,D) <=>
    ($greater(Y,0) & ?[L:$int]:
      (is_days_in_month(M,Y,L) & $greater(D,0) & $lesseq(D,L))))).

% Weekday code used by the Gregorian form of Zeller's congruence:
% 0=Saturday, 1=Sunday, ..., 6=Friday.
tff(map_i0, axiom, map_iso(0,saturday)).
tff(map_i1, axiom, map_iso(1,sunday)).
tff(map_i2, axiom, map_iso(2,monday)).
tff(map_i3, axiom, map_iso(3,tuesday)).
tff(map_i4, axiom, map_iso(4,wednesday)).
tff(map_i5, axiom, map_iso(5,thursday)).
tff(map_i6, axiom, map_iso(6,friday)).
tff(map_n0, axiom, map_name_to_int(saturday,0)).
tff(map_n1, axiom, map_name_to_int(sunday,1)).
tff(map_n2, axiom, map_name_to_int(monday,2)).
tff(map_n3, axiom, map_name_to_int(tuesday,3)).
tff(map_n4, axiom, map_name_to_int(wednesday,4)).
tff(map_n5, axiom, map_name_to_int(thursday,5)).
tff(map_n6, axiom, map_name_to_int(friday,6)).
tff(map_iso_functional, axiom,
  ![I:$int,N1:day_name,N2:day_name]:
   ((map_iso(I,N1) & map_iso(I,N2)) => N1=N2)).
tff(map_name_functional, axiom,
  ![N:day_name,I1:$int,I2:$int]:
   ((map_name_to_int(N,I1) & map_name_to_int(N,I2)) => I1=I2)).
tff(weekday_functional, axiom,
  ![Dt:date,N1:day_name,N2:day_name]:
   ((weekday(Dt,N1) & weekday(Dt,N2)) => N1=N2)).

% Zeller, January/February. The displayed and encoded formula both use -2J.
tff(zeller_janfeb, axiom,
 ![Y:$int,M:$int,D:$int,Name:day_name,ZY:$int,ZM:$int,K:$int,J:$int,
   T1:$int,T2:$int,H:$int]:
  ((valid_date(Y,M,D) & (M=1 | M=2) &
    ZY=$difference(Y,1) & ZM=$sum(M,12) &
    K=$remainder_e(ZY,100) & J=$quotient_e(ZY,100) &
    T1=$quotient_e($product(13,$sum(ZM,1)),5) &
    T2=$difference(
         $sum(D,$sum(T1,$sum(K,$sum($quotient_e(K,4),$quotient_e(J,4))))),
         $product(2,J)) &
    H=$remainder_e(T2,7) & map_iso(H,Name))
   => weekday(ymd(Y,M,D),Name))).

% Zeller, March--December.
tff(zeller_mardec, axiom,
 ![Y:$int,M:$int,D:$int,Name:day_name,K:$int,J:$int,T1:$int,T2:$int,H:$int]:
  ((valid_date(Y,M,D) & $lesseq(3,M) & $lesseq(M,12) &
    K=$remainder_e(Y,100) & J=$quotient_e(Y,100) &
    T1=$quotient_e($product(13,$sum(M,1)),5) &
    T2=$difference(
         $sum(D,$sum(T1,$sum(K,$sum($quotient_e(K,4),$quotient_e(J,4))))),
         $product(2,J)) &
    H=$remainder_e(T2,7) & map_iso(H,Name))
   => weekday(ymd(Y,M,D),Name))).
'''

CORE_T2 = r'''
% ==============================================================================
% TIER 2 CORE: date/time normalization and scheduling (no accelerators yet)
% ==============================================================================
tff(t_time, type, time: $tType).
tff(t_dt, type, dt: ($int * $int * $int * $int * $int) > time).
tff(dt_injective, axiom,
 ![Y1:$int,M1:$int,D1:$int,H1:$int,Min1:$int,
   Y2:$int,M2:$int,D2:$int,H2:$int,Min2:$int]:
  (dt(Y1,M1,D1,H1,Min1)=dt(Y2,M2,D2,H2,Min2) =>
   (Y1=Y2 & M1=M2 & D1=D2 & H1=H2 & Min1=Min2))).

tff(t_calc_date, type, calc_date: ($int * $int * $int * date) > $o).
tff(t_norm_time, type, normalize_time: ($int * $int * $int * $int * $int * $int * $int) > $o).
tff(t_calc_datetime, type, calc_datetime: ($int * $int * $int * $int * $int * $int * $int * $int * time) > $o).
tff(t_valid_day, type, valid_day: $int > $o).
tff(valid_day_def, axiom, ![D:$int]: (valid_day(D) <=> ($greater(D,0) & $lesseq(D,31)))).

% calc_date uses a one-based day index relative to the first day of (Y,M):
% index 1 is the first day; index 0 is the preceding day.
tff(calc_date_base, axiom,
 ![D:$int,M:$int,Y:$int,L:$int]:
  ((is_days_in_month(M,Y,L) & $greater(D,0) & $lesseq(D,L))
   => calc_date(D,M,Y,ymd(Y,M,D)))).

tff(calc_date_fwd_month, axiom,
 ![D:$int,M:$int,Y:$int,L:$int,Res:date]:
  ((is_days_in_month(M,Y,L) & $greater(D,L) & $less(M,12) &
    calc_date($difference(D,L),$sum(M,1),Y,Res))
   => calc_date(D,M,Y,Res))).

tff(calc_date_fwd_year, axiom,
 ![D:$int,Y:$int,L:$int,Res:date]:
  ((is_days_in_month(12,Y,L) & $greater(D,L) &
    calc_date($difference(D,L),1,$sum(Y,1),Res))
   => calc_date(D,12,Y,Res))).

tff(calc_date_back_month, axiom,
 ![D:$int,M:$int,Y:$int,L:$int,Res:date]:
  (($lesseq(D,0) & $greater(M,1) &
    is_days_in_month($difference(M,1),Y,L) &
    calc_date($sum(D,L),$difference(M,1),Y,Res))
   => calc_date(D,M,Y,Res))).

tff(calc_date_back_year, axiom,
 ![D:$int,Y:$int,L:$int,Res:date]:
  (($lesseq(D,0) & $greater(Y,1) & is_days_in_month(12,$difference(Y,1),L) &
    calc_date($sum(D,L),12,$difference(Y,1),Res))
   => calc_date(D,1,Y,Res))).

tff(calc_date_functional, axiom,
 ![D:$int,M:$int,Y:$int,R1:date,R2:date]:
  ((calc_date(D,M,Y,R1) & calc_date(D,M,Y,R2)) => R1=R2)).

% Exact mixed-radix time normalization (Euclidean quotient/remainder).
tff(time_normalization, axiom,
 ![SH:$int,SM:$int,AH:$int,AM:$int,EH:$int,EM:$int,DD:$int,
   TotalM:$int,CarryH:$int,TotalH:$int]:
  ((TotalM=$sum(SM,AM) & EM=$remainder_e(TotalM,60) &
    CarryH=$quotient_e(TotalM,60) & TotalH=$sum(SH,$sum(AH,CarryH)) &
    EH=$remainder_e(TotalH,24) & DD=$quotient_e(TotalH,24))
   => normalize_time(SH,SM,AH,AM,EH,EM,DD))).

tff(time_normalization_functional, axiom,
 ![SH:$int,SM:$int,AH:$int,AM:$int,H1:$int,M1:$int,D1:$int,H2:$int,M2:$int,D2:$int]:
  ((normalize_time(SH,SM,AH,AM,H1,M1,D1) & normalize_time(SH,SM,AH,AM,H2,M2,D2))
   => (H1=H2 & M1=M2 & D1=D2))).

tff(datetime_composition, axiom,
 ![Y:$int,M:$int,D:$int,H:$int,Min:$int,AD:$int,AH:$int,AM:$int,
   RY:$int,RM:$int,RD:$int,RH:$int,RMin:$int,TDD:$int]:
  ((normalize_time(H,Min,AH,AM,RH,RMin,TDD) &
    calc_date($sum(D,$sum(AD,TDD)),M,Y,ymd(RY,RM,RD)))
   => calc_datetime(Y,M,D,H,Min,AD,AH,AM,dt(RY,RM,RD,RH,RMin)))).

tff(datetime_functional, axiom,
 ![Y:$int,M:$int,D:$int,H:$int,Min:$int,AD:$int,AH:$int,AM:$int,R1:time,R2:time]:
  ((calc_datetime(Y,M,D,H,Min,AD,AH,AM,R1) & calc_datetime(Y,M,D,H,Min,AD,AH,AM,R2))
   => R1=R2)).

% Scheduler relations.
tff(t_nth_offset, type, calc_nth_offset: ($int * $int * $int) > $o).
tff(t_nth_weekday, type, nth_weekday_date: ($int * day_name * $int * $int * date) > $o).
tff(t_last_weekday, type, last_weekday_date: (day_name * $int * $int * date) > $o).

tff(nth_offset_def, axiom,
 ![S:$int,T:$int,O:$int]:
  (calc_nth_offset(S,T,O) <=>
   ($lesseq(0,S) & $lesseq(S,6) & $lesseq(0,T) & $lesseq(T,6) &
    O=$remainder_e($sum($difference(T,S),7),7)))).

tff(nth_weekday_def, axiom,
 ![N:$int,DName:day_name,M:$int,Y:$int,D:$int]:
  (nth_weekday_date(N,DName,M,Y,ymd(Y,M,D)) <=>
   ($greater(N,0) & $lesseq(N,5) &
    ?[L:$int,SName:day_name,SI:$int,TI:$int,O:$int]:
     (is_days_in_month(M,Y,L) & weekday(ymd(Y,M,1),SName) &
      map_name_to_int(SName,SI) & map_name_to_int(DName,TI) &
      calc_nth_offset(SI,TI,O) &
      D=$sum(1,$sum(O,$product($difference(N,1),7))) &
      $greater(D,0) & $lesseq(D,L))))).

tff(nth_weekday_functional, axiom,
 ![N:$int,W:day_name,M:$int,Y:$int,R1:date,R2:date]:
  ((nth_weekday_date(N,W,M,Y,R1) & nth_weekday_date(N,W,M,Y,R2)) => R1=R2)).

tff(last_weekday_def, axiom,
 ![W:day_name,M:$int,Y:$int,D:$int]:
  (last_weekday_date(W,M,Y,ymd(Y,M,D)) <=>
   (valid_date(Y,M,D) & weekday(ymd(Y,M,D),W) &
    ?[L:$int]: (is_days_in_month(M,Y,L) & $greater($sum(D,7),L))))).

tff(last_weekday_functional, axiom,
 ![W:day_name,M:$int,Y:$int,R1:date,R2:date]:
  ((last_weekday_date(W,M,Y,R1) & last_weekday_date(W,M,Y,R2)) => R1=R2)).

% Exact Gregorian year-span arithmetic used by sound jump accelerators.
tff(t_leaps_before, type, leap_days_before: ($int * $int) > $o).
tff(t_year_span, type, year_span_days: ($int * $int * $int) > $o).

tff(leaps_before_def, axiom,
 ![Y:$int,L:$int]:
  (leap_days_before(Y,L) <=>
   ($greater(Y,0) &
    L=$sum(
       $difference($quotient_e($difference(Y,1),4),$quotient_e($difference(Y,1),100)),
       $quotient_e($difference(Y,1),400))))).

tff(year_span_days_def, axiom,
 ![Y:$int,N:$int,Days:$int]:
  (year_span_days(Y,N,Days) <=>
   ($greater(Y,0) & $greater(N,0) &
    ?[L1:$int,L2:$int]:
     (leap_days_before(Y,L1) & leap_days_before($sum(Y,N),L2) &
      Days=$sum($product(365,N),$difference(L2,L1)))))).
'''

ACCELS = {
'1y': r'''
tff(accel_fwd_1y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days(Y,1,J) & $greater(D,J) & calc_date($difference(D,J),1,$sum(Y,1),R))
   => calc_date(D,1,Y,R))).
tff(accel_back_1y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days($difference(Y,1),1,J) & $lesseq(D,0) &
    calc_date($sum(D,J),1,$difference(Y,1),R))
   => calc_date(D,1,Y,R))).
''',
'4y': r'''
tff(accel_fwd_4y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days(Y,4,J) & $greater(D,J) & calc_date($difference(D,J),1,$sum(Y,4),R))
   => calc_date(D,1,Y,R))).
tff(accel_back_4y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days($difference(Y,4),4,J) & $lesseq(D,0) &
    calc_date($sum(D,J),1,$difference(Y,4),R))
   => calc_date(D,1,Y,R))).
''',
'10y': r'''
tff(accel_fwd_10y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days(Y,10,J) & $greater(D,J) & calc_date($difference(D,J),1,$sum(Y,10),R))
   => calc_date(D,1,Y,R))).
tff(accel_back_10y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days($difference(Y,10),10,J) & $lesseq(D,0) &
    calc_date($sum(D,J),1,$difference(Y,10),R))
   => calc_date(D,1,Y,R))).
''',
'100y': r'''
tff(accel_fwd_100y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days(Y,100,J) & $greater(D,J) & calc_date($difference(D,J),1,$sum(Y,100),R))
   => calc_date(D,1,Y,R))).
tff(accel_back_100y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days($difference(Y,100),100,J) & $lesseq(D,0) &
    calc_date($sum(D,J),1,$difference(Y,100),R))
   => calc_date(D,1,Y,R))).
''',
'400y': r'''
tff(accel_fwd_400y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days(Y,400,J) & $greater(D,J) & calc_date($difference(D,J),1,$sum(Y,400),R))
   => calc_date(D,1,Y,R))).
tff(accel_back_400y, axiom,
 ![D:$int,Y:$int,J:$int,R:date]:
  ((year_span_days($difference(Y,400),400,J) & $lesseq(D,0) &
    calc_date($sum(D,J),1,$difference(Y,400),R))
   => calc_date(D,1,Y,R))).
''',
'month_hopper': r'''
tff(accel_weekday_month_hop, axiom,
 ![Y:$int,M:$int,W:day_name,WI:$int,L:$int,NWI:$int,NW:day_name]:
  ((weekday(ymd(Y,M,1),W) & is_days_in_month(M,Y,L) & $less(M,12) &
    map_name_to_int(W,WI) & NWI=$remainder_e($sum(WI,L),7) & map_iso(NWI,NW))
   => weekday(ymd(Y,$sum(M,1),1),NW))).
tff(accel_weekday_year_hop, axiom,
 ![Y:$int,W:day_name,WI:$int,L:$int,NWI:$int,NW:day_name]:
  ((weekday(ymd(Y,12,1),W) & is_days_in_month(12,Y,L) &
    map_name_to_int(W,WI) & NWI=$remainder_e($sum(WI,L),7) & map_iso(NWI,NW))
   => weekday(ymd($sum(Y,1),1,1),NW))).
''',
'weekday400': r'''
tff(accel_weekday_400y, axiom,
 ![Y:$int,M:$int,D:$int,W:day_name]:
  ((valid_date(Y,M,D) & valid_date($sum(Y,400),M,D) & weekday(ymd(Y,M,D),W))
   => weekday(ymd($sum(Y,400),M,D),W))).
'''
}

# T3 uses only independently generated intermediate ground lemmas, not direct answers
# to the 200 benchmark conjectures.
def leap_before(y:int)->int:
    z=y-1
    return z//4-z//100+z//400

def span_days(y:int,n:int)->int:
    return 365*n + leap_before(y+n)-leap_before(y)

def weekday_name(y,m,d):
    return ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'][datetime.date(y,m,d).weekday()]

anchors=[]
for y in (2024,2025):
    for m in range(1,13):
        w=weekday_name(y,m,1)
        anchors.append(f'tff(anchor_wk_{y}_{m}_1, axiom, weekday(ymd({y},{m},1),{w})).')
for y in (1600,1776,1900,1969,1985,2000,2024,2025,2034):
    for n in (4,10,100,400):
        anchors.append(f'tff(anchor_span_{y}_{n}, axiom, year_span_days({y},{n},{span_days(y,n)})).')
for y in (1900,2000,2024,2025,2100,2400):
    L=29 if calendar.isleap(y) else 28
    anchors.append(f'tff(anchor_feb_{y}, axiom, is_days_in_month(2,{y},{L})).')
ANCHORS='\n% --- T3 validated intermediate ground lemmas ---\n'+'\n'.join(anchors)+'\n'

# Write tiers.
t1 = T1
core = T1 + CORE_T2
full = core + ''.join(ACCELS[k] for k in ('1y','4y','10y','100y','400y','month_hopper','weekday400'))
t3 = full + ANCHORS
(TDIR/'T1_structural.tff').write_text(t1)
(TDIR/'T2_core_no_accel.tff').write_text(core)
(TDIR/'T2_full_sound.tff').write_text(full)
(TDIR/'T3_validated_anchors.tff').write_text(t3)

# Add-one and leave-one-out variants.
for k,v in ACCELS.items():
    (ADIR/f'ADD1__{k}.tff').write_text(core+v)
    loo=core+''.join(vv for kk,vv in ACCELS.items() if kk!=k)
    (ADIR/f'LOO__{k}.tff').write_text(loo)

manifest={
 'tiers': ['T1_structural.tff','T2_core_no_accel.tff','T2_full_sound.tff','T3_validated_anchors.tff'],
 'accelerator_components': list(ACCELS),
 't3_anchor_count': len(anchors),
 't3_anchor_policy': 'intermediate only: month-start weekdays, exact year-span lengths, February lengths; no direct 200-query calc_date answers'
}
(ADIR/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('[OK] generated sound T1/T2/T3 and ablation variants')
print(json.dumps(manifest,indent=2))
